ADD_LIBRARY(curl SHARED IMPORTED GLOBAL)
SET_PROPERTY(TARGET cudart PROPERTY IMPORTED_LOCATION ${CURL_LIBRARIES})
MESSAGE(STATUS "curl library: ${CURL_LIBRARIES}")

INCLUDE_DIRECTORIES(${CURL_INCLUDE_DIRS})
